Global:
  use_gpu: True
  epoch_num: 80
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/svtr_ctc/
  save_epoch_step: 5
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model: PaddleOCR/output/rec/svtr_ctc/best_accuracy
  checkpoints:
  save_inference_dir: ./inference/svtr/
  infer_mode: False
  use_visualdl: False
  character_dict_path: stat_dict.txt
  max_text_length: 25
  save_res_path: ./output/rec/predicts_svtr.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: L2
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Neck:
    name: SequenceEncoder
    encoder_type: rnn  
    hidden_size: 256
    num_layers: 2
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode
  character_dict_path: stat_dict.txt
  use_space_char: True

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/gbiel/CRK-AutoRoller/data
    label_file_list: ["C:/Users/gbiel/CRK-AutoRoller/data/images/label.txt"]
    transforms:
      - DecodeImage:
          channel_first: False
          img_mode: BGR
      - CTCLabelEncode:
          character_dict_path: C:/Users/gbiel/CRK-AutoRoller/stat_dict.txt
          use_space_char: True
      - RecAug:
          aug_ops:
            ColorJitter:
              brightness: 0.2
              contrast: 0.2
              hue: 0.1
              saturation: 0.2
            RandomColor: None
          prob: 0.3
          aug_prob: 0.8
          padding: True
          use_crop: False
          use_rotate: False
      - RecResizeImg:
          image_shape: [3, 32, 330]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: True
    batch_size_per_card: 16
    drop_last: True
    num_workers: 0
    use_shared_memory: False
    use_mp: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/gbiel/CRK-AutoRoller/data
    label_file_list: ["C:/Users/gbiel/CRK-AutoRoller/data/eval/label.txt"]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
          character_dict_path: C:/Users/gbiel/CRK-AutoRoller/stat_dict.txt
          use_space_char: True
      - RecResizeImg:
          image_shape: [3, 32, 330]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: False
    batch_size_per_card: 16
    drop_last: False
    num_workers: 0
    use_shared_memory: False
    use_mp: False
