Global:
  use_gpu: False
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/resnet18_bilstm_ctc/
  save_epoch_step: 5
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model:
  checkpoints:
  save_inference_dir: ./inference/resnet18/
  infer_mode: False
  use_visualdl: False
  character_dict_path: /Users/grantbiellak/PycharmProjects/CRK-AutoRoller/stat_dict.txt
  max_text_length: 70
  save_res_path: ./output/rec/predicts_resnet18.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: L2
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 18
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0
    out_channels: 37  # <-- Will be auto-calculated based on stat_dict.txt

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode
  character_dict_path: /Users/grantbiellak/PycharmProjects/CRK-AutoRoller/stat_dict.txt
  use_space_char: True

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /Users/grantbiellak/PycharmProjects/CRK-AutoRoller/data
    label_file_list: ["/Users/grantbiellak/PycharmProjects/CRK-AutoRoller/data/train.txt"]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
          character_dict_path: /Users/grantbiellak/PycharmProjects/CRK-AutoRoller/stat_dict.txt
          use_space_char: True
      - RandAugment:
          magnitude: 6
      - RecResizeImg:
          image_shape: [3, 32, 320]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label']
  loader:
    shuffle: True
    batch_size_per_card: 2
    drop_last: True
    num_workers: 2

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /Users/grantbiellak/PycharmProjects/CRK-AutoRoller/data
    label_file_list: ["/Users/grantbiellak/PycharmProjects/CRK-AutoRoller/data/val.txt"]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
          character_dict_path: /Users/grantbiellak/PycharmProjects/CRK-AutoRoller/stat_dict.txt
          use_space_char: True
      - RecResizeImg:
          image_shape: [3, 32, 320]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label']
  loader:
    shuffle: False
    batch_size_per_card: 2
    drop_last: False
    num_workers: 2
