Global:
  use_gpu: True
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/resnet18_bilstm_ctc/
  save_epoch_step: 2
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model: 
  checkpoints: C:\Users\gbiel\CRK-AutoRoller\PaddleOCR\output\rec\resnet18_bilstm_ctc\latest.pdparams
  save_inference_dir: ./inference/resnet18/
  infer_mode: False
  use_visualdl: False
  character_dict_path: C:\Users\gbiel\CRK-AutoRoller\stat_dict.txt
  max_text_length: 70
  save_res_path: ./output/rec/predicts_resnet18.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0001
  regularizer:
    name: L2
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 18
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode
  character_dict_path: C:/Users/gbiel/CRK-AutoRoller/stat_dict.txt
  use_space_char: True

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/gbiel/CRK-AutoRoller/data
    label_file_list: ["C:/Users/gbiel/CRK-AutoRoller/data/images/label.txt"]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
          character_dict_path: C:\Users\gbiel\CRK-AutoRoller\stat_dict.txt
          use_space_char: True
      - RandAugment:
          magnitude: 1
      - RecResizeImg:
          image_shape: [3, 32, 320]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: True
    batch_size_per_card: 16  # Keep low for smooth multitasking
    drop_last: True
    num_workers: 0          # Avoid CPU overload
    use_shared_memory: False
    use_mp: False

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:/Users/gbiel/CRK-AutoRoller/data
    label_file_list: ["C:/Users/gbiel/CRK-AutoRoller/data/eval/label.txt"]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
          character_dict_path: C:\Users\gbiel\CRK-AutoRoller\stat_dict.txt
          use_space_char: True
      - RecResizeImg:
          image_shape: [3, 32, 320]
          padding: True
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: False
    batch_size_per_card: 16
    drop_last: False
    num_workers: 0
    use_shared_memory: False
    use_mp: False
